/*
 * Copyright (C) 2015 TYONLINE TECHNOLOGY PTY. LTD.
 *
 */

package au.com.tyo.app;

/**
 * @author Eric Tang <eric.tang@tyo.com.au>
 */

public interface Constants {

	int MESSAGE_NETWORK_READY = 88888;
	
	int MESSAGE_NETWORK_DISCONNECTED = 99999;
	
	int MESSAGE_SUGGESTION_RETURN = 99;

	int MESSAGE_BACKGROUND_TASK_STARTED = 0;

	int MESSAGE_BACKGROUND_TASK_ENDDED = 1;

	int MESSAGE_BACKGROUND_TASK_STAGE_ONE = 11;
	int MESSAGE_BACKGROUND_TASK_STAGE_TWO = 12;
	int MESSAGE_BACKGROUND_TASK_STAGE_THREE = 13;
	int MESSAGE_BACKGROUND_TASK_STAGE_FOUR = 14;
	int MESSAGE_BACKGROUND_TASK_STAGE_FIVE = 15;
	int MESSAGE_BACKGROUND_TASK_STAGE_SIX = 16;

	int MESSAGE_CUSTOM_ONE = 21;
	int MESSAGE_CUSTOM_TWO = 22;
	int MESSAGE_CUSTOM_THREE = 23;
	int MESSAGE_CUSTOM_FOUR = 24;
	int MESSAGE_CUSTOM_FIVE = 25;
	int MESSAGE_CUSTOM_SIX = 26;
	int MESSAGE_CUSTOM_SEVEN = 27;
	int MESSAGE_CUSTOM_EIGHT = 28;
	int MESSAGE_CUSTOM_NINE = 29;
	int MESSAGE_CUSTOM_TEN = 30;

	// SPLASH SCREEN
	int MESSAGE_AD_LOADED = 99;

	int MESSAGE_AD_FAILED = -1;

	int MESSAGE_AD_TIMEUP = -2;

	int MESSAGE_APP_INITIALIZED = 1000;
}
